spring:
  application:
    name: takitransfer
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    open-in-view: false
    properties:
      hibernate:
        default_schema: "takitransfer"
        order_inserts: true
        order_updates: true
        default_batch_fetch_size: 50
        jdbc:
          batch_size: 50
        generate_statistics: false
  flyway:
    baseline-on-migrate: true
    locations: classpath:/db/migrations
    schemas: "takitransfer"
    default-schema: "takitransfer"

logging:
  level:
    root: info
    org:
      zalando:
        logbook: trace
      apache:
        http:
          wire: debug
  pattern:
    console: '%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger.%M - %msg%n'